<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Views\Aboutus\" />
    <Folder Include="Views\AllServisec\" />
    <Folder Include="Views\RegistrationForm\" />
    <Folder Include="Views\SignUp2\" />
  </ItemGroup>

</Project>
